dashboard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # Manager-related actions
    url(r'^index/(?P<reset>\d+)?$', views.managers.index,
        name='index'),
    url(r'^index/$', views.managers.index,
        name='index'),
    url(r'^domains$', views.managers.domain_summary,
        name='domain-summary'),
    # url(r'^domain/(?P<domain_type>\d+)/$', views.managers.set_domain,
    #     name='set-domain'),

    url(r'^manager/new/(?P<domain_id>[\S]+)$', views.managers.create_manager,
        name='create-manager'),
    url(r'^manager/(?P<manager_id>[\S]+)/$', views.managers.connect_manager,
        name='connect-manager'),
    url(r'^manager/disconnect/(?P<manager_id>[\S]+)/$', views.managers.disconnect_manager,
        name='disconnect-manager'),
    url(r'^manager/delete/(?P<manager_id>[\S]+)/delete$', views.managers.delete_manager,
        name='delete-manager'),

    # component-related actions
    url(r'^components/(?P<component_id>[\S]+)/deployments/$', views.deployments.list,
        name='list-deployments'),
    url(r'^components/(?P<component_id>[\S]+)/deployments/(?P<wait>[\S]+)/$', views.deployments.list,
        name='list-deployments-delayed'),
    url(r'^components/unlink/(?P<component_id>[\S]+)$', views.blueprints.unlink,
        name="unlink-blueprint"),
    url(r'^components/create/$', views.components.create,
        name='create-component'),
    url(r'^components/(?P<component_id>[\S]+)/delete/$', views.components.delete,
        name='delete-component'),

    # Blueprint-related actions
    url(r'^components/(?P<component_id>[\S]+)/blueprints/create/$', views.blueprints.create,
        name='create-blueprint'),
    url(r'^components/(?P<component_id>[\S]+)/$', views.components.show,
        name='show-component'),
    url(r'^components/(?P<component_id>[\S]+)/blueprints/link/(?P<blueprint_id>[\S]+)$',
        views.blueprints.link,
        name='link-blueprint'),

    # url(r'^blueprints/push/(?P<blueprint_name>[\S]+)$', views.blueprints.push_local_blueprint, name='push-blueprint'),
    url(r'^blueprints/save/(?P<blueprint_name>[\S]+)$', views.blueprints.serve,
        name='serve-blueprint'),
    url(r'^blueprints/get/(?P<blueprint_name>[\S]+)/candidates/$', views.blueprints.get_candidates,
        name='get-blueprint-candidates'),
    url(r'^blueprints/get/(?P<blueprint_name>[\S]+)/candidates/assign/(?P<filename>[\S]+)$',
        views.blueprints.assign_blueprint_file,
        name='assign-blueprint-file'),

    url(r'^blueprints/files/(?P<blueprint_name>[\S]+)/$', views.blueprints.show_files,
        name='show-blueprint-files'),
    url(r'^blueprints/delete/(?P<blueprint_name>[\S]+)/$', views.blueprints.delete,
        name='delete-blueprint'),

    # Blueprint script-related actions
    url(r'^blueprints/(?P<blueprint_name>[\S]+)/scripts/create/$', views.scripts.create_script,
        name='create-script'),
    url(r'^blueprints/scripts/(?P<script_id>[\S]+)/delete/$', views.scripts.delete_script,
        name='delete-script'),
    url(r'^scripts/(\d+)/get/$', views.scripts.get_script,
        name='get-script'),

    url(r'^deployments/(?P<blueprint_id>[\S]+)/(?P<deployment_id>[\S]+)/delete/$', views.deployments.delete,
        name='delete-deployment'),
    url(r'^blueprints/(?P<blueprint_id>[\S]+)/run/$', views.deployments.start,
        name='run-deployment'),
    url(r'^blueprints/(?P<blueprint_name>[\S]+)/create/$', views.deployments.create,
        name='create-deployment'),
    url(r'^executions/(?P<deployment_name>[\S]+)/(?P<execution_id>[\S]+)$', views.executions.get_events,
        name='get-execution-events'),
    url(r'^deployments/(?P<deployment_id>[\S]+)/get/$', views.deployments.get,
        name='get-deployment'),


    # Authentication
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/login'}, name='logout'),
    url(r'^register/$', views.authentication.register_user, name='register'),

    url(r'^$', views.managers.index),
]

dashboard/models.py
import logging
import os
import shutil
import tarfile
import time
import utils
import yaml

from django.conf import settings
from django.db import models
from itsdangerous import base64_encode
from cloudify_rest_client.executions import Execution

logger = logging.getLogger(__name__)

INSTALL = 'install'
UNINSTALL = 'uninstall'
EXECUTE = 'execute_operation'

WORKFLOWS = (
    (INSTALL, 'Install'),
    (UNINSTALL, 'Uninstall'),
    (EXECUTE, 'Execute operation')
)


#    workflow_id = models.CharField(max_length=20, choices=WORKFLOWS, default=INSTALL, null=True)

class Domain(models.Model):
    trusted = models.BooleanField(default=True)

    AWS = 'Amazon Web Services'
    OS = 'OpenStack'
    CS = "CloudStack"
    VMW = "VMWare"

    PUBLIC_CLOUD_PROVIDERS = (
        (AWS, 'Amazon Web Services'),
    )

    PRIVATE_CLOUD_PROVIDERS = (
        (OS, 'OpenStack'),
        (CS, 'CloudStack'),
        (VMW, 'VMWare'),
    )
    PROVIDERS = PUBLIC_CLOUD_PROVIDERS + PRIVATE_CLOUD_PROVIDERS

    def get_name(self):
        return "trusted" if self.trusted else "untrusted"

    def get_cloud_providers(self):
        if self.trusted:
            return self.PRIVATE_CLOUD_PROVIDERS
        return self.PUBLIC_CLOUD_PROVIDERS


class Manager(models.Model):
    domain = models.ForeignKey(Domain, null=True)
    provider = models.CharField(max_length=20, default=Domain.OS, choices=Domain.PROVIDERS, null=True)

    ip = models.CharField(max_length=20, unique=False) # Just for the sake of review (to simulate manager in the untrusted domain)
    connected = models.BooleanField(default=False)
    authenticated = models.BooleanField(default=False)
    ssl = models.BooleanField(default=False)
    last_used = models.DateTimeField(null=True)

    def __unicode__(self):
        return u'%s - %s, requires authentication=%s' % (self.ip, self.provider, self.authenticated)

    def get_protocol(self):
        return "https" if self.ssl else "http"

    def get_port(self):
        return 443 if self.ssl else 80

    # Gets managers status with the help of cloudify's rest client
    def get_status(self):
        from cloudify_rest_client.exceptions import UserUnauthorizedError
        from requests import ConnectionError

        try:
            client = self.get_client()
            return client.manager.get_status().get('status')
        except ConnectionError:
            return "connection failed"
        except UserUnauthorizedError:
            client = self.get_authenticated_client()
            try:
                status = client.manager.get_status().get('status')
                self.authenticated = True
                self.save()
                return status
            except Exception as e:
                return str(e)
        except Exception as e:
            return str(e)

    def get_client(self):
        from cloudify_rest_client import CloudifyClient
        if self.authenticated:
            return self.get_authenticated_client()
        return CloudifyClient(host=self.ip, protocol=self.get_protocol(), port=self.get_port(), trust_all=True)

    def get_authenticated_client(self):
        from cloudify_rest_client import CloudifyClient
        headers = self.get_headers()
        return CloudifyClient(host=self.ip, protocol=self.get_protocol(), port=self.get_port(), trust_all=True,
                              headers=headers)

    def get_headers(self):
        authentication = self.get_authentication_token_header()
        authorization = self.get_authorization_header()
        return dict(authentication.items() + authorization.items())

    def get_authorization_header(self):
        # Read environment variables to get credentials
        username = os.environ.get(settings.CFY_USERNAME, False)
        password = os.environ.get(settings.CFY_PASSWORD, False)
        credentials = '{0}:{1}'.format(username, password)
        return {'Authorization': 'Basic ' + base64_encode(credentials)}

    def get_authentication_token_header(self):
        import uuid
        token = uuid.uuid4().hex
        return {'Authentication-Token': token}

# Represents application to be deployed, for instance Crypton
class Component(models.Model):
    WITDOM_COMPONENT_TYPES = (
        ('PC', 'Protection component'),
        ('PO', 'Protection Orchestrator'),
        ('B', 'Broker'),
        ('S', 'Service'),
        ('DB', 'Storage'),
        ('IAM', 'Identity and Access Management'),
        ('KM', 'Key manager')
    )

    NONE = 0
    DEPLOYING = 1
    SUCCESS = 2
    FAILURE = 3
    UNDEPLOYING = 4

    STATUSES = (
        (NONE, 'not deployed'),
        (DEPLOYING, 'deploy in progress'),
        (SUCCESS, 'successfuly deployed'),
        (FAILURE, 'deploy failed'),
        (UNDEPLOYING, 'undeploy in progress'),
    )

    name = models.CharField(max_length=100, blank=False) #, unique=True
    type = models.CharField(max_length=50, default='S', choices=WITDOM_COMPONENT_TYPES, null=False)
    provider = models.CharField(max_length=30, blank=False, null=True)
    description = models.CharField(default=None, null=True, max_length=500, blank=True)
    deployed = models.BooleanField(default=False)
    manager = models.ForeignKey(Manager, null=True)
    status = models.IntegerField(choices=STATUSES, default=NONE)

    def __unicode__(self):
        return u'%s' % self.name

    #def get_status_tag(self):
    #    return "deployed" if self.deployed else "not deployed"

    def refresh_status(self):
        from cloudify_rest_client.exceptions import CloudifyClientError
        self.status = self.NONE
        if hasattr(self, 'blueprint'):
            if self.blueprint.deployment_set.count():
                deployment = self.blueprint.deployment_set.first()
                try:
                    deployment_status = deployment.get_status()
                    if deployment_status == 0:
                        self.status = self.DEPLOYING
                    elif deployment_status == 1:
                        self.status = self.SUCCESS
                    elif deployment_status == 2:
                        self.status = self.FAILURE
                    elif deployment_status == 4:
                        self.status = self.UNDEPLOYING
                except CloudifyClientError as e:
                    pass # deployment doesn't exist on Cloudify manager anymore
        self.save()

    def get_status(self):
        self.refresh_status()
        return self.STATUSES[self.status][0]

    def get_status_str(self):
        return self.STATUSES[self.status][1]

    # Deletes all blueprint related folders associated with this app
    def cleanup(self):
        try:
            shutil.rmtree('uploads/' + self.name)
            self.blueprint.remove_downloaded_files()
        except Blueprint.DoesNotExist:
            logger.info("Tried to remove downloaded blutprint, but did not exist")
        except Exception as e:
            logger.info("Exception ocurred when deleting component %s (removing uploads folder)", self.name)

class Blueprint(models.Model):
    name = models.CharField(max_length=100, blank=False, unique=True, default="")
    created_at = models.DateTimeField(null=True)
    plan = models.CharField(max_length=2000, null=True)
    # Associated with blueprints originating from workstation
    local_filename = models.CharField(max_length=100,
                                      null=True)  # Name of the blueprint file which is stored locally
    local_filepath = models.CharField(max_length=300,
                                      null=True)  # Path (including local_filename) at which blueprint file is accessible
    uploaded = models.BooleanField(default=True)

    # Associated with blueprints originating from the Cloudify management server
    downloaded = models.BooleanField(default=False)
    component = models.OneToOneField(Component,
                                     null=True)  # Can exist on the management server, but is unassigned to the application

    def __unicode__(self):
        return u'%s' % self.name

    def get_folder_path(self):
        if self.downloaded:
            return 'downloads/{}/{}'.format(self.name, self.name)
        else:
            return 'uploads/{}/{}'.format(self.component.name, self.name)

    def get_file_path(self):
        if self.local_filepath:
            folder = self.local_filepath  # Remote blueprint was not uploaded from this dashboard and does not obey our hierarchy
        else:
            folder = self.get_folder_path()  # Remote blueprint was uploaded from this dashboard

        return folder + '/' + self.local_filename

    def display_yaml_file(self):
        return open(self.get_file_path()).read()

    def get_extract_path(self):
        path = 'downloads/' + self.name
        if not os.path.exists(path):
            os.makedirs(path)
        return path

    def rename_blueprint_folder(self, path):
        for file in os.listdir(path):
            filepath = os.path.join(path, file)
            if os.path.isdir(filepath):
                os.rename(os.path.join(path, file), os.path.join(path, self.name))

    def extract_archive(self):
        extract_path = self.get_extract_path()
        archive = "{}.tar.gz".format(extract_path)
        tar = tarfile.open(archive)
        tar.extractall(path=extract_path)
        self.rename_blueprint_folder(extract_path)
        tar.close()
        os.remove(archive)

    def download_remote_files(self):
        extract_path = self.get_extract_path()
        cloudify_client = self.component.manager.get_client()
        cloudify_client.blueprints.download(self.name, output_file="{}.tar.gz".format(extract_path))
        self.extract_archive()
        self.downloaded = True


    def remove_downloaded_files(self):
        shutil.rmtree(self.get_extract_path())


    def associate_blueprint_file(self):
        folder = self.get_folder_path()
        blueprint_file = None
        for file in os.listdir(folder):

dashboard/views/authentication.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.http import require_http_methods, require_GET
from ..forms import ExtendedUserCreationForm


# Logs in authenticated user
@require_http_methods(["GET", "POST"])
def login_user(request):
    user = authenticate(username=request.POST['username'],
                        password=request.POST['password'])
    if user is not None:
        if user.is_active:  # Account was not cancelled
            login(request, user)
    user = User.objects.create_user
    user.save()


# Log out current user
@require_GET
def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/login')


# Registers a new user
@require_http_methods(["GET", "POST"])
def register_user(request):
    # User provides his account settings
    if request.method == 'POST':
        form = ExtendedUserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            user = authenticate(username=request.POST['username'],
                                password=request.POST['password1'])
            login(request, user)
            return HttpResponseRedirect('/index')
        else:
            messages.error(request, form.errors)
        return render(request, "registration/register.html", {'form': form})
    # GET, show registration form
    else:
        form = ExtendedUserCreationForm()
        return render(request, "registration/register.html", {'form': form})

dashboard/views/components.py
import os
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET, require_POST
from django.contrib import messages
from .. import forms, models, synchronize


@login_required
@require_GET
def show(request, component_id):
    component = models.Component.objects.get(id=component_id)
    component_blueprint = models.Blueprint.objects.filter(component=component).first()
    request.session['step'] = 3
    request.session['component'] = component

    if component_blueprint is not None:
        return redirect('list-deployments', component_id)
    manager = component.manager
    synchronize.sync_database(manager.get_client())
    all_blueprints = models.Blueprint.objects.all()
    available_blueprints = [b for b in all_blueprints if b.component is None]

    params = {'blueprint_form': forms.BlueprintForm(),
              'component': component,
              'blueprint': component_blueprint,
              'blueprints': available_blueprints
              }

    return render(request, 'dashboard/component/componentDetails.html', params)


@login_required
@require_POST
def create(request):
    form = forms.ComponentForm(request.POST)

    if form.is_valid():
        app = form.save()  # Save to database
        manager_id = request.session["manager"].id
        manager = models.Manager.objects.get(id=manager_id)
        app.manager = manager
        app.save()
        # TODO
        os.makedirs('uploads/' + app.name)  # Create directory for this app within uploads folder
    else:
        messages.error(request, form.errors)

    return redirect('index')


# Deletes application entry without modification of related deployments, executions and blueprints either in DB or on management server
@login_required
@require_GET
def delete(request, component_id):
    component = models.Component.objects.get(id=component_id)
    component.cleanup()
    component.delete()
    request.session['step'] = 2
    if request.session.has_key('component'):
        del request.session['component']
    return redirect('index')

dashboard/templates/dashboard/blueprint/blueprint.html
{% extends "dashboard/base.html" %}

{% load bootstrap3 %}

{% bootstrap_css %}         <!-- Load CSS -->
{% bootstrap_javascript %}  <!-- Load JS -->

{% block title %} WITDOM | {{ blueprint.name }} {% endblock %}

{% block content %}
   <div class="container">
{#        {% with component=blueprint.component %}#}
{#            <h2 class="brown"><b>{{ component.name }}</b> - {{ component.get_type_display }}</h2>#}
{#            <p>{{ component.description }}, authored by {{ component.author }}</p>#}
{#        {% endwith %}#}

        <nav class="navbar navbar-default topSpacing">
            <div class="container-fluid">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                    {% with component=blueprint.component %}
                        <a class="navbar-brand" href="#"><h3 class="brown brandText"><b>{{ component.name }}</b> - {{ component.get_type_display }}</h3></a>
                    {% endwith %}
                </div>

                <div class="collapse navbar-collapse" id="main-nav">
                <ul class="nav navbar-nav">
                    <li class=""><a href="{% url 'show-component' blueprint.component.id %}"> Deployment info</a></li>
                    <li><a href="{% url 'show-blueprint-files' blueprint.name %}">Deployment files</a></li>
                    <li><a href="{% url 'serve-blueprint' blueprint.name %}"><span class="glyphicon glyphicon-save"></span> Save files</a></li>
                </ul>
                 <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Remove blueprint<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'delete-blueprint' blueprint.name %}">Delete from Cloudify manager</a></li>
                            <li><a href="{% url 'unlink-blueprint' blueprint.component.id %}">Remove, but keep on manager</a></li>
                        </ul>
                    </li>
                </ul>
                </div>
            </div>
        </nav>

       {% bootstrap_messages %}

        <div class="col-md-9" id="details">
            {% block details %}{% endblock %}
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/blueprint/blueprintCandidates.html
{% extends "dashboard/blueprint/blueprint.html" %}

{% block details_title %} Assign blueprint file {% endblock %}

{% block details %}

    <p class="bottomSpacing">
        <i>When uploading a blueprint to Cloudify manager, Cloudify packages whole directory containing the main blueprint file and uploads it along with it.
    However, we could not automatically determine which .yaml file holds the contents of this blueprint.</i> <br/>
    </p>

    <h4>Please select a file from the list below.<br/></h4>
    <p class="bottomSpacing"><i>If selected blueprint contains references to any script configuration files, they will be automatically added.<br/></i></p>

    {% for blueprintFile in blueprintCandidates %}
        <p>
             <a href="{% url 'assign-blueprint-file' blueprint.name blueprintFile %}">{{ blueprintFile }}</a>
        </p>
    {% endfor %}



{% endblock %}

dashboard/templates/dashboard/blueprint/blueprintFiles.html
{% extends "dashboard/blueprint/blueprint.html" %}

{% block details %}

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
<div class="panel panel-default">
    <ul class="nav nav-tabs">
        <li role="presentation" class="active"><a data-toggle="tab" href="#file-blueprint-main">Main blueprint file</a></li>
        <li role="presentation"><a data-toggle="tab" href="#file-blueprint-inputs">Blueprint inputs</a></li>

        {% if blueprint.script_set.count %}
            <li role="presentation"><a data-toggle="tab" href="#file-scripts">Additional scripts</a></li>
        {% endif %}
    </ul>
    <div class="panel-body">
        <div class="tab-content">
            <div class="tab-pane fade in active" id="file-blueprint-main">
                {% include 'dashboard/blueprint/mainBlueprintFile.html' %}
            </div>
            <div class="tab-pane fade" id="file-blueprint-inputs">
                {% include 'dashboard/blueprint/blueprintInputsFile.html' %}
            </div>
            <div class="tab-pane fade" id="file-scripts">
                {% include 'dashboard/scripts.html' %}
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

dashboard/templates/dashboard/blueprint/blueprintInfo.html
{% extends "dashboard/blueprint/blueprint.html" %}

{% block details_title %} General information {% endblock %}

{% block details %}

{% if blueprint.uploaded %}
    Created at <strong><i>{{ blueprint.created_at }}</i></strong><br/>

    {% if blueprint.local_filename %}
        <h5>Blueprint file: <strong>{{ blueprint.local_filename }}</strong></h5>
    {% endif %}

    {% if blueprint.deployment_set.count %}
        <h5>Deployments: {{ blueprint.deployment_set.count }}</h5>
    {% else %}
        <h5><i>There are currently no deployments for selected blueprint.</i></h5>
    {% endif %}

    <hr>
{#    {% include 'dashboard/newDeployment.html' %} <!-- Form for creating new deployment -->#}

{% else %}
    This blueprint only exists locally. <br/>

    <div>
        <br/>
        <h4>Upload additional scripts?</h4>
        <p>Before uploading blueprint to Cloudify manager, you can optionally add configuration scripts for your app's nodes. Note that you won't be able to add scripts after you have uploaded this blueprint to Cloudify manager.</p>
        <br/>

        <p><b>All files in the folder from which you uploaded the blueprint will be automatically uploaded on the Cloudify Manager. If your scripts reside inside your blueprint folder, there is no need to upload them seperately.</b></p>
        <form action="{% url 'create-script' blueprint.name %}" enctype="multipart/form-data" method="post" class="hInline">
            {% csrf_token %}
            <span class="btn btn-default btn-file">
                Add script <input type="file" onchange="this.form.submit();" id="id_file" name="file" class="btn-file">
            </span>
            <input type="hidden" name="hidden" value="{{ blueprint.name }}"/>
        </form>
    </div>

    <br/>
    <a href="{% url 'push-blueprint' blueprint.name %}" class="btn btn-success topSpacing" role="button"><span class="glyphicon glyphicon-cloud-upload"></span> Upload to Cloudify management server</a>
{% endif %}

{% endblock %}

dashboard/templates/dashboard/blueprint/blueprintInputsFile.html
{% load pygmentify %}

<h4>{{ deployment.local_inputs_filename }}</h4>

{% pygment %}
    <pre lang="yaml">
        {{ deployment.read_inputs }}
    </pre>
{% endpygment %}

dashboard/templates/dashboard/blueprint/blueprintSummary.html
{% load bootstrap3 %}

<h2><a href="{% url 'list-deployments' component.id %}">{{ blueprint.name }}</a></h2>
    {% if blueprint.uploaded %}
        {% bootstrap_label "On Cloudify manager" label_class="label label-success" %}
    {% else  %}
        {% bootstrap_label "Local" label_class="label label-default" %}
    {% endif %}

<div class="topSpacing">
    <a href="{% url 'delete-blueprint' blueprint.name %}" class="btn btn-danger" role="button"><span class="glyphicon glyphicon-trash"></span></a>
    <a href="{% url 'unlink-blueprint' component.id %}" class="btn btn-default" role="button"><span class="glyphicon glyphicon-link"></span> Unlink from app</a>
</div>

dashboard/templates/dashboard/blueprint/blueprintUploadForm.html
{% if not component.deployed %}
<h4>Provide data for deployment</h4>
<p>Here you should provide application blueprint and inputs for this deployment.<br/>
    If your blueprint references any lifecycle scripts, you can add them here.</p>
<br/>
<b>You can start the deployment in the next step.</b>
<br/>
<br/>

<form id="component-deployment-files" class="form-inline" action="{% url 'create-blueprint' component.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
        <div class="form-group col-md-5 col-md-offset-3">
        <input type="text" id="id_name" name='name' class="form-control" placeholder="Unique blueprint name">
        <span class="btn btn-default btn-file">
            Choose Cloudify blueprint
            <input type="file" id="id_blueprint_file" name="blueprint_file" class="btn-file">
        </span>
        </div>
        <span id="filename_blueprint" class="col-md-2 text-left fileFeedback">No file chosen</span>
    </div>

    <div class="row topSpacing">
        <div class="form-group col-md-5 col-md-offset-3">
            <input type="text" class="form-control" id="id_name" name='deployment_name' placeholder="Unique deployment name">
            <span class="btn btn-default btn-file">
                Choose deployment inputs <input type="file" id="id_blueprint_inputs_file" name="blueprint_inputs_file" class="btn-file">
            </span>
        </div>
        <span id="filename_blueprint_inputs" class="col-md-2 text-left fileFeedback">No file chosen</span>
    </div>

    <div class="row">
        <div class="form-group">
            <span id="addScriptSpan" class="btn btn-primary btn-file topSpacing">
                Add script <input type="file" id="id_script_file" name="script_file" class="btn-file">
            </span>
            <br/>
            <div id="scriptsFeedbackDiv" style="display:none;" class="topSpacing">Scripts: <span id="scriptsList"></span></div>
        </div>
    </div>

    <button type="submit" class="btn btn-success topSpacing">
        <span class="glyphicon glyphicon-cloud-upload"></span>
        Upload to Cloudify manager
    </button>
</form>


{% else %}
    Your application was already deployed!
{% endif %}

dashboard/templates/dashboard/blueprint/existingBlueprints.html
{% load bootstrap3 %}
{% bootstrap_css %}         <!-- Load CSS -->
{% bootstrap_javascript %}  <!-- Load JS -->

{% if blueprints %}
    <div class="list-group topSpacing">
    {% for blueprint in blueprints %}
            <a href="{% url 'link-blueprint' component.id blueprint.id %}" class="btn btn-default" role="button"> <span> {{ blueprint.name }}</span></a>
    {% endfor %}
    </div>
{% endif %}

dashboard/templates/dashboard/blueprint/mainBlueprintFile.html
{% load pygmentify %}

<h4>{{ blueprint.local_filename }}</h4>

{% pygment %}
    <pre lang="yaml">
        {{ blueprint.display_yaml_file }}
    </pre>
{% endpygment %}